### ISSUE TITLE
Guide?

### ISSUE THREAD

**Issue by Boscop** [alex/ct-tools#12]
Hi, what are the exact steps one has to take to get SSL  on a Rust server (e.g. with the rocket crate)?
E.g. on CentOS, do I have to do this? https://certbot.eff.org/#centosrhel7-other
And then how should this crate be used?
Do I have to add a route in my server to serve some of the files that the certbot generated?
Does the certbot generate the pem files?
Would you recommend running the rust server behind nginx, does that make the SSL situation easier?

What is the difference between letsencrypt-auto and certbot?
The only instructions I can find are for servers like apache, nginx etc. not for custom made servers (like rust based).

**Comment by alex** [comment]
This doesn't have anything to do with certbot, if you're interested in certbot you should ask questions there.

This does provide integration between the rustls TLS library and letsencrypt -- an example of configuring it is here: https://github.com/alex/ct-tools/blob/master/src/main.rs#L212-L224
