### ISSUE TITLE
build fails over missing method in futures-await

### ISSUE THREAD

**Issue by JJvdBerge** [alex/ct-tools#22]
During building I get the error:

`error[E0599]: no method named "resume" found for type "T" in the current scope
   --> /home/jochem/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-await-0.1.1/src/lib.rs:120:35
    |
120 |             match unsafe { self.0.resume() } {
    |                                   ^^^^^^
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item "resume", perhaps you need to implement it:
            candidate #1: "std::ops::Generator"`

Config is Ubuntu 16.04 LTS with `rustc 1.35.0-nightly (719b0d984 2019-03-13).`

**Comment by alex** [comment]
Yeah, the current churn in the `async` ecosystem has broken this on recent nightlies. You can find one from a month or two ago that still builds, and hopefully eventually #19 will get to a state where I can merge it.

**Comment by alex** [comment]
This is fixed, master now builds on a recent nightly!
